import assert from 'node:assert/strict';
import { account,request,mailToken,mailOtp,cleanup,prefix,password,base } from './helpers.mjs';
try {
  const apiOrigin=new URL(base).origin;
  for (const path of ['/api/v1/live','/api/v1/ready']) {
    const response=await fetch(apiOrigin+path);
    assert.equal(response.status,200,`${path} must report healthy while the smoke environment is running`);
    assert.equal(response.headers.get('x-content-type-options'),'nosniff');
    assert.equal(response.headers.get('x-frame-options'),'DENY');
    assert.ok(response.headers.get('x-correlation-id'),'Operational responses must include a correlation ID');
  }
  const owner=await account('owner'),member=await account('member'),outsider=await account('outsider');
  const token=owner.accessToken;
  const org=await request('/organizations',{token,body:{name:prefix,slug:prefix}});
  assert.ok((await request('/organizations',{token})).some(o=>o.id===org.id));
  const project=await request('/projects',{token,body:{organizationId:org.id,name:'Launch project',description:'Real workflow',status:'ACTIVE',startDate:'2026-09-01',dueDate:'2026-10-20'}});
  await request(`/projects/${project.id}/members`,{token,body:{userId:outsider.userId,role:'CONTRIBUTOR'},status:400});
  await request(`/organizations/${org.id}/invitations`,{token,body:{email:member.email,role:'MEMBER'}});
  const invitation=await mailToken(member.email,'Join');
  await request('/organizations/invitations/accept',{token:outsider.accessToken,body:{token:invitation},status:400});
  await request('/organizations/invitations/accept',{token:member.accessToken,body:{token:invitation}});
  await request(`/projects/${project.id}/members`,{token,body:{userId:member.userId,role:'CONTRIBUTOR'},status:204});
  const task=await request(`/projects/${project.id}/tasks`,{token,body:{title:'Test task',description:'Before',status:'TO DO',priority:'HIGH',dueDate:'2026-10-01',assigneeIds:[owner.userId,member.userId]}});
  await request(`/tasks?projectId=${project.id}`,{token:outsider.accessToken,status:403});
  await request(`/tasks/${task.id}`,{method:'PATCH',token:member.accessToken,body:{status:'IN PROGRESS'}});
  await request(`/organizations/${org.id}/members/${member.userId}`,{method:'PATCH',token,body:{role:'GUEST'},status:204});
  await request(`/tasks/${task.id}`,{method:'PATCH',token:member.accessToken,body:{status:'DONE'},status:403});
  await request(`/tasks/${task.id}`,{method:'PATCH',token,body:{title:'Updated task',status:'DONE',description:'After',clearDueDate:true,assigneeIds:[member.userId]}});
  const loaded=(await request(`/tasks?projectId=${project.id}`,{token})).data.find(t=>t.id===task.id);
  assert.equal(loaded.title,'Updated task');assert.equal(loaded.dueDate,null);assert.ok(loaded.completedAt);assert.deepEqual(loaded.assigneeIds,[member.userId]);
  const metrics=await request(`/dashboard/metrics?projectId=${project.id}`,{token});
  assert.deepEqual(metrics,{myTasks:0,overdueTasks:0,completedTasks:1,inProgressTasks:0,totalTasks:1});
  await request(`/tasks/${task.id}/comments`,{token,body:{content:'Review this',mentionedUserIds:[member.userId],parentCommentId:null}});
  assert.equal((await request(`/tasks/${task.id}/comments`,{token}))[0].content,'Review this');
  await request(`/tasks/${task.id}/comments`,{token:member.accessToken,body:{content:'Not allowed',mentionedUserIds:[],parentCommentId:null},status:404});
  const file=new FormData();file.append('file',new Blob(['attachment content'],{type:'text/plain'}),'smoke.txt');
  const attachment=await request(`/tasks/${task.id}/attachments`,{token,body:file});
  const download=await fetch(`${base}/attachments/${attachment.id}/download`,{headers:{Authorization:'Bearer '+token}});assert.equal(download.status,200);assert.equal(await download.text(),'attachment content');
  await request(`/attachments/${attachment.id}/download`,{token:outsider.accessToken,status:404});
  const notices=await request('/notifications',{token:member.accessToken});assert.ok(notices.length>=2);
  await request('/notifications/read-all',{method:'PATCH',token:member.accessToken,status:204});assert.ok((await request('/notifications',{token:member.accessToken})).every(n=>n.isRead));
  await request('/account',{method:'PATCH',token,body:{firstName:'Updated',lastName:'Owner',timezone:'Africa/Nairobi'}});assert.equal((await request('/account',{token})).firstName,'Updated');
  await request(`/projects/${project.id}`,{method:'PATCH',token,body:{name:'Edited project',description:'Saved',status:'ON_HOLD',startDate:null,dueDate:null}});
  assert.equal((await request(`/projects/${project.id}`,{token})).name,'Edited project');
  await request('/auth/forgot-password',{body:{email:owner.email}});const reset=await mailToken(owner.email,'Reset');
  await request('/auth/reset-password',{body:{token:reset,password:password+'new'}});
  await request('/auth/reset-password',{body:{token:reset,password:password+'again'},status:400});
  await request('/auth/login',{body:{email:owner.email,password},status:401});
  await request('/auth/refresh',{body:{refreshToken:owner.refreshToken},status:401});
  const challenge=await request('/auth/login',{body:{email:owner.email,password:password+'new'}});assert.equal(challenge.requiresOtp,true);
  const login=await request('/auth/verify-otp',{body:{email:owner.email,code:await mailOtp(owner.email)}});
  const renewed=await request('/auth/refresh',{body:{refreshToken:login.refreshToken}});assert.ok(renewed.accessToken);
  await request('/auth/logout',{token:renewed.accessToken,body:{refreshToken:renewed.refreshToken},status:204});
  await request('/auth/refresh',{body:{refreshToken:renewed.refreshToken},status:401});
  const graphql=await fetch(base.replace('/api/v1','/graphql'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:'{ serviceName }'})});
  assert.equal(graphql.status,401);
  await request(`/tasks/${task.id}`,{method:'DELETE',token,status:204});assert.equal((await request(`/tasks?projectId=${project.id}`,{token})).data.length,0);
  await request(`/projects/${project.id}`,{method:'DELETE',token,status:204});assert.equal((await request(`/projects?organizationId=${org.id}`,{token})).length,0);
  await request(`/tasks?projectId=${project.id}`,{token,status:403});
  console.log('PASS: health checks, security headers, accounts, organizations, invitations, projects, dashboard metrics, task editing, role isolation, comments, attachments, notifications, password reset, refresh, logout, and archival.');
} finally { cleanup(); }
