import { chromium } from 'playwright-core';
import assert from 'node:assert/strict';
import { account,request,mailToken,cleanup,prefix,password } from './helpers.mjs';
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
 const owner=await account('owner'),guest=await account('guest');const token=owner.accessToken;
 const org=await request('/organizations',{token,body:{name:prefix,slug:prefix}});
 const project=await request('/projects',{token,body:{organizationId:org.id,name:'Team project',status:'ACTIVE'}});
 const context=await browser.newContext();const page=await context.newPage();page.setDefaultTimeout(30000);
 async function login(p,user){await p.getByLabel('Email address').fill(user.email);await p.getByLabel('Password',{exact:true}).fill(password);await p.getByRole('button',{name:'Log in',exact:true}).click();}
 await page.goto('http://127.0.0.1:5173/#login',{waitUntil:'domcontentloaded'});await login(page,owner);
 await page.locator('.sidebar').getByRole('button',{name:'Members',exact:true}).click();await page.getByRole('button',{name:'Invite teammate',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Email address').fill(guest.email);await dialog.getByLabel('Role',{exact:true}).selectOption('GUEST');await dialog.getByRole('button',{name:'Send invitation',exact:true}).click();await dialog.waitFor({state:'hidden'});await page.getByText(guest.email,{exact:true}).waitFor();
 const invitation=await mailToken(guest.email,'Join');const guestContext=await browser.newContext();const guestPage=await guestContext.newPage();guestPage.setDefaultTimeout(30000);await guestPage.goto('http://127.0.0.1:5173/#invite?token='+encodeURIComponent(invitation),{waitUntil:'domcontentloaded'});await login(guestPage,guest);await guestPage.getByRole('button',{name:'Accept invitation',exact:true}).click();await guestPage.getByRole('heading',{name:'No project selected',exact:true}).waitFor();assert.equal(await guestPage.getByRole('button',{name:'New project',exact:true}).count(),0);
 await page.reload();await page.locator('.members-panel').getByText(guest.email,{exact:true}).waitFor();await page.getByRole('button',{name:'Team project',exact:true}).click();await page.getByRole('button',{name:'Add project member',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Organization member',{exact:true}).selectOption(guest.userId);await dialog.getByLabel('Role',{exact:true}).selectOption('VIEWER');await dialog.getByRole('button',{name:'Add member',exact:true}).click();await dialog.waitFor({state:'hidden'});await page.locator('.members-panel').getByText(guest.email,{exact:true}).waitFor();
 await guestPage.reload();await guestPage.getByRole('heading',{name:'Team project',exact:true}).waitFor();assert.equal(await guestPage.getByRole('button',{name:'New task',exact:true}).count(),0);assert.equal(await guestPage.getByRole('button',{name:'Project settings',exact:true}).count(),0);
 await request(`/projects/${project.id}/tasks`,{token,body:{title:'Notification target',status:'TO DO',priority:'LOW',assigneeIds:[owner.userId]}});await page.reload();await page.getByRole('button',{name:'Notifications',exact:true}).first().click();await page.locator('.notification-panel').getByRole('button',{name:/You were assigned to Notification target/}).click();await page.getByRole('dialog').getByLabel('Task title').waitFor();assert.equal(await page.getByRole('dialog').getByLabel('Task title').inputValue(),'Notification target');await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.locator('.sidebar').getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Edit project',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Project name').fill('Updated team project');await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await dialog.waitFor({state:'hidden'});await page.getByRole('heading',{name:'Updated team project',exact:true}).waitFor();
 await page.locator('.sidebar').getByRole('button',{name:'Settings',exact:true}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Archive project',exact:true}).click();await page.getByRole('button',{name:'Edit project',exact:true}).waitFor({state:'hidden'});
 console.log('PASS: UI invitations, invitation sign-in, guest onboarding, project membership, viewer controls, notification task navigation, project settings, and archival.');
} finally {await browser.close();cleanup();}
