import { useMemo, useState } from 'react';
import { Alert, Box, CircularProgress, MenuItem, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import { api, dateLabel } from './api';
import type { AdminOrganization, AdminProject, AdminUser } from './types/admin';

type Page = 'users' | 'organizations' | 'projects';
const copy: Record<Page, { title:string; description:string; endpoint:string }> = {
  users: { title:'Users', description:'Manage and monitor registered TaskFlow accounts.', endpoint:'/admin/users' },
  organizations: { title:'Organizations', description:'View organizations across the TaskFlow platform.', endpoint:'/admin/organizations' },
  projects: { title:'Projects', description:'Read-only oversight of projects across the platform.', endpoint:'/admin/projects' }
};

export default function AdminManagement({ page }: { page:Page }) {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const info = copy[page];
  const query = useQuery<AdminUser[] | AdminOrganization[] | AdminProject[]>({ queryKey:['admin', page], queryFn:() => api.get(info.endpoint).then(response => response.data), staleTime:30_000 });
  const rows = useMemo(() => (query.data ?? []).filter(row => JSON.stringify(row).toLowerCase().includes(search.toLowerCase())).filter(row => page !== 'projects' || !status || (row as AdminProject).status === status), [query.data, search, status, page]);
  return <Box sx={{ p:{ xs:2, md:3 } }}><Typography variant="h4" component="h1">{info.title}</Typography><Typography color="text.secondary" sx={{ mt:1, mb:3 }}>{info.description}</Typography><Box sx={{ display:'flex', gap:2, flexWrap:'wrap', mb:3 }}><TextField size="small" label={`Search ${info.title.toLowerCase()}`} value={search} onChange={event => setSearch(event.target.value)} sx={{ minWidth:260 }}/>{page === 'projects' && <TextField select size="small" label="Status" value={status} onChange={event => setStatus(event.target.value)} sx={{ minWidth:180 }}><MenuItem value="">All statuses</MenuItem>{['PLANNING','ACTIVE','ON_HOLD','COMPLETED'].map(value => <MenuItem value={value} key={value}>{value}</MenuItem>)}</TextField>}</Box>{query.isLoading && <Box sx={{ py:6, textAlign:'center' }}><CircularProgress/></Box>}{query.error && <Alert severity="error">Unable to load {info.title.toLowerCase()}.</Alert>}{!query.isLoading && !query.error && rows.length === 0 && <Alert severity="info">No {info.title.toLowerCase()} found.</Alert>}{rows.length > 0 && <TableContainer component={Paper}><Table size="small" aria-label={`${info.title} table`}><TableHead><TableRow>{page === 'users' ? <><TableCell>User</TableCell><TableCell>Email</TableCell><TableCell>Account ID</TableCell><TableCell>Organizations</TableCell><TableCell>Registered</TableCell></> : page === 'organizations' ? <><TableCell>Organization</TableCell><TableCell>Owner</TableCell><TableCell>Members</TableCell><TableCell>Projects</TableCell><TableCell>Created</TableCell></> : <><TableCell>Project</TableCell><TableCell>Organization</TableCell><TableCell>Status</TableCell><TableCell>Tasks</TableCell><TableCell>Due date</TableCell></>}</TableRow></TableHead><TableBody>{rows.map(row => page === 'users' ? <UserRow key={row.id} row={row as AdminUser}/> : page === 'organizations' ? <OrganizationRow key={row.id} row={row as AdminOrganization}/> : <ProjectRow key={row.id} row={row as AdminProject}/>)}</TableBody></Table></TableContainer>}</Box>;
}
function UserRow({ row }:{row:AdminUser}) { return <TableRow><TableCell>{row.firstName} {row.lastName}</TableCell><TableCell>{row.email}</TableCell><TableCell><Typography variant="caption">{row.id}</Typography></TableCell><TableCell>{row.organizationCount}</TableCell><TableCell>{dateLabel(row.createdAt)}</TableCell></TableRow>; }
function OrganizationRow({ row }:{row:AdminOrganization}) { return <TableRow><TableCell><strong>{row.name}</strong><br/><Typography variant="caption">{row.slug}</Typography></TableCell><TableCell>{row.owner ?? 'No owner found'}</TableCell><TableCell>{row.memberCount}</TableCell><TableCell>{row.projectCount}</TableCell><TableCell>{dateLabel(row.createdAt)}</TableCell></TableRow>; }
function ProjectRow({ row }:{row:AdminProject}) { return <TableRow><TableCell>{row.name}</TableCell><TableCell>{row.organizationName ?? 'Unknown'}</TableCell><TableCell>{row.archivedAt ? 'ARCHIVED' : row.status}</TableCell><TableCell>{row.taskCount}</TableCell><TableCell>{dateLabel(row.dueDate ?? undefined)}</TableCell></TableRow>; }
