CREATE TABLE users (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    first_name NVARCHAR(100) NOT NULL,
    last_name NVARCHAR(100) NOT NULL,
    email NVARCHAR(320) NOT NULL UNIQUE,
    password_hash NVARCHAR(500) NOT NULL,
    avatar_url NVARCHAR(2000) NULL,
    timezone NVARCHAR(100) NOT NULL DEFAULT 'UTC',
    status NVARCHAR(30) NOT NULL DEFAULT 'active',
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE refresh_tokens (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    user_id UNIQUEIDENTIFIER NOT NULL REFERENCES users(id),
    token_hash NVARCHAR(128) NOT NULL UNIQUE,
    expires_at DATETIME2 NOT NULL,
    revoked_at DATETIME2 NULL,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    last_used_at DATETIME2 NULL
);

CREATE TABLE organizations (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    name NVARCHAR(200) NOT NULL UNIQUE,
    slug NVARCHAR(200) NOT NULL UNIQUE,
    logo NVARCHAR(2000) NULL,
    timezone NVARCHAR(100) NOT NULL DEFAULT 'UTC',
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE organization_members (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    user_id UNIQUEIDENTIFIER NOT NULL REFERENCES users(id),
    organization_id UNIQUEIDENTIFIER NOT NULL REFERENCES organizations(id),
    role NVARCHAR(30) NOT NULL,
    joined_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    status NVARCHAR(30) NOT NULL DEFAULT 'active',
    CONSTRAINT uq_organization_members UNIQUE (organization_id, user_id)
);

CREATE TABLE organization_invitations (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    organization_id UNIQUEIDENTIFIER NOT NULL REFERENCES organizations(id),
    email NVARCHAR(320) NOT NULL,
    role NVARCHAR(30) NOT NULL,
    token_hash NVARCHAR(128) NOT NULL UNIQUE,
    expires_at DATETIME2 NOT NULL,
    accepted_at DATETIME2 NULL,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE password_reset_tokens (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    user_id UNIQUEIDENTIFIER NOT NULL REFERENCES users(id),
    token_hash NVARCHAR(128) NOT NULL UNIQUE,
    expires_at DATETIME2 NOT NULL,
    used_at DATETIME2 NULL
);

CREATE TABLE projects (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    organization_id UNIQUEIDENTIFIER NOT NULL REFERENCES organizations(id),
    name NVARCHAR(200) NOT NULL,
    description NVARCHAR(MAX) NULL,
    owner_id UNIQUEIDENTIFIER NOT NULL REFERENCES users(id),
    status NVARCHAR(30) NOT NULL DEFAULT 'PLANNING',
    start_date DATETIME2 NULL,
    due_date DATETIME2 NULL,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    archived_at DATETIME2 NULL
);

CREATE TABLE project_members (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    project_id UNIQUEIDENTIFIER NOT NULL REFERENCES projects(id),
    user_id UNIQUEIDENTIFIER NOT NULL REFERENCES users(id),
    role NVARCHAR(30) NOT NULL,
    joined_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    status NVARCHAR(30) NOT NULL DEFAULT 'active',
    CONSTRAINT uq_project_members UNIQUE (project_id, user_id)
);

CREATE TABLE tasks (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    project_id UNIQUEIDENTIFIER NOT NULL REFERENCES projects(id),
    parent_task_id UNIQUEIDENTIFIER NULL REFERENCES tasks(id),
    title NVARCHAR(300) NOT NULL,
    description NVARCHAR(MAX) NULL,
    status NVARCHAR(40) NOT NULL DEFAULT 'TO DO',
    priority NVARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    start_date DATETIME2 NULL,
    due_date DATETIME2 NULL,
    created_by UNIQUEIDENTIFIER NOT NULL REFERENCES users(id),
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    completed_at DATETIME2 NULL,
    deleted_at DATETIME2 NULL
);

CREATE TABLE task_assignees (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    task_id UNIQUEIDENTIFIER NOT NULL REFERENCES tasks(id),
    user_id UNIQUEIDENTIFIER NOT NULL REFERENCES users(id),
    assigned_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    status NVARCHAR(30) NOT NULL DEFAULT 'active',
    CONSTRAINT uq_task_assignees UNIQUE (task_id, user_id)
);

CREATE TABLE comments (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    task_id UNIQUEIDENTIFIER NOT NULL REFERENCES tasks(id),
    user_id UNIQUEIDENTIFIER NOT NULL REFERENCES users(id),
    parent_comment_id UNIQUEIDENTIFIER NULL REFERENCES comments(id),
    content NVARCHAR(MAX) NOT NULL CHECK (DATALENGTH(content) <= 20000),
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    deleted_at DATETIME2 NULL
);

CREATE TABLE comment_mentions (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    comment_id UNIQUEIDENTIFIER NOT NULL REFERENCES comments(id),
    user_id UNIQUEIDENTIFIER NOT NULL REFERENCES users(id),
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT uq_comment_mentions UNIQUE (comment_id, user_id)
);

CREATE TABLE attachments (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    task_id UNIQUEIDENTIFIER NULL REFERENCES tasks(id),
    comment_id UNIQUEIDENTIFIER NULL REFERENCES comments(id),
    uploaded_by UNIQUEIDENTIFIER NOT NULL REFERENCES users(id),
    file_name NVARCHAR(500) NOT NULL,
    file_url NVARCHAR(2000) NOT NULL,
    file_type NVARCHAR(200) NULL,
    file_size BIGINT NOT NULL,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    deleted_at DATETIME2 NULL,
    CONSTRAINT ck_attachment_parent CHECK (task_id IS NOT NULL OR comment_id IS NOT NULL)
);

CREATE TABLE notifications (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    user_id UNIQUEIDENTIFIER NOT NULL REFERENCES users(id),
    type NVARCHAR(50) NOT NULL,
    message NVARCHAR(2000) NOT NULL,
    entity_type NVARCHAR(50) NOT NULL,
    related_id UNIQUEIDENTIFIER NULL,
    is_read BIT NOT NULL DEFAULT 0,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
