param(
    [string]$GmailAddress,
    [string]$FrontendUrl = 'http://127.0.0.1:5173'
)

$ErrorActionPreference = 'Stop'
$workspace = Split-Path -Parent $PSScriptRoot
$project = Join-Path $workspace 'src\Pms.Api\Pms.Api.csproj'

if (-not $GmailAddress) { $GmailAddress = Read-Host 'Gmail address to send from' }
$GmailAddress = $GmailAddress.Trim()
try { $address = New-Object System.Net.Mail.MailAddress($GmailAddress) }
catch { throw 'Enter a valid Gmail or Google Workspace email address.' }
if ($address.Address -ne $GmailAddress) { throw 'Enter only your email address, without a display name.' }
$frontend = $null
if (-not [Uri]::TryCreate($FrontendUrl, [UriKind]::Absolute, [ref]$frontend) -or $frontend.Scheme -notin @('http','https')) {
    throw 'FrontendUrl must be a complete http or https address.'
}

Write-Host 'Use a Google App Password, not your normal Google password.'
Write-Host 'Create one at https://myaccount.google.com/apppasswords with 2-Step Verification enabled.'
$securePassword = Read-Host 'Google App Password (input hidden)' -AsSecureString
$previous = @{}
$keys = @('Smtp__Host','Smtp__Port','Smtp__EnableSsl','Smtp__From','Smtp__Username','Smtp__Password','FrontendUrl')
foreach ($key in $keys) { $previous[$key] = [Environment]::GetEnvironmentVariable($key, 'Process') }
try {
    $appPassword = (New-Object System.Net.NetworkCredential('', $securePassword)).Password -replace '\s', ''
    if ($appPassword -notmatch '^[a-zA-Z]{16}$') { throw 'Expected the 16-letter App Password generated by Google.' }

    # Restart only this workspace's API. Never stop an unrelated listener.
    $listeners = @(Get-NetTCPConnection -LocalPort 5141 -State Listen -ErrorAction SilentlyContinue)
    $apiRoot = [System.IO.Path]::GetFullPath((Join-Path $workspace 'src\Pms.Api')) + [System.IO.Path]::DirectorySeparatorChar
    foreach ($processId in ($listeners.OwningProcess | Sort-Object -Unique)) {
        $running = Get-Process -Id $processId -ErrorAction Stop
        if (-not $running.Path -or $running.ProcessName -ne 'Pms.Api' -or -not $running.Path.StartsWith($apiRoot, [StringComparison]::OrdinalIgnoreCase)) {
            throw 'Port 5141 is used by another application. Stop that application before continuing.'
        }
        Stop-Process -Id $processId -ErrorAction Stop
        Wait-Process -Id $processId -Timeout 10 -ErrorAction SilentlyContinue
    }

    $env:Smtp__Host = 'smtp.gmail.com'
    $env:Smtp__Port = '587'
    $env:Smtp__EnableSsl = 'true'
    $env:Smtp__From = $GmailAddress
    $env:Smtp__Username = $GmailAddress
    $env:Smtp__Password = $appPassword
    $env:FrontendUrl = $FrontendUrl.TrimEnd('/')
    $appPassword = $null
    Write-Host 'Starting TaskFlow with Gmail delivery. Credentials are not saved to files.'
    Write-Host 'Request a fresh password reset in the app to test delivery. Press Ctrl+C to stop.'
    & dotnet run --project $project --urls http://localhost:5141
    if ($LASTEXITCODE -ne 0) { throw 'The API stopped with an error. Review the output above.' }
} finally {
    $appPassword = $null
    foreach ($key in $keys) { [Environment]::SetEnvironmentVariable($key, $previous[$key], 'Process') }
    $securePassword.Dispose()
}
